### PR TITLE
Ranger

### PR DESCRIPTION
**Pull request by rdinnager**
Hey Dan! I quickly whipped up a new function for fitting `ranger` random forests. I'm sending it to develop in case you want to change it before it goes to master. I had to change `marginal.plots`, `env.breadth`, `env.overlap` and `env.evaluate` to deal with yet another weird `predict` function for `ranger` models.  I also noticed a random error (which may not have caused any major problems) in `enmtools.rf` where there was a `family = "binomial"` argument in the `randomForest` call. So I took it out. Edit: This closes issue #78 .

Cheers!

### CODE REVIEW

**Comment by rdinnager** [comment]
I forgot to reference issue #78 . I wonder if it will work if I put it in this comment?

**Comment by danlwarren** [comment]
Oh right on, glad you noticed that!  I'm sure it was just a copy/paste leftover from when I adapted the GLM template for RF.  RF was just ignoring the argument as far as I know, but it's still better to just remove it!

**Comment by danlwarren** [comment]
Oh hey, when I try to do visualize.enm on a ranger model I get:

 Error in predict.ranger(model$model, newdata = plot.df, type = "response") : 
  Error: Argument 'data' is required for non-quantile prediction. 

Any idea what's up with that?

**Comment by danlwarren** [comment]
Oh this highlighted something I borked up: the marginal plots function wasn't standardizing so that the max predicted suitability was 1, which was hiding a lot of the shape of the RF functions.  I've now set it up so that there's a "standardize" argument which defaults to TRUE.  Unless that argument is set to FALSE, marginal plots will now have a max response value of 1.

This is on the dev branch right now, so if you want to do more tweaking on a new branch you might want to update from there first.

**Comment by rdinnager** [comment]
Ah nuts.  Forgot about visualize.enm. it's the same issue as why i had to
change env.breadth et al e.g. weird ranger predict function. Is easy fix.
I'll get to it tomorrow.

On 2 Mar 2018 2:17 AM, "Dan Warren" <notifications@github.com> wrote:

Oh hey, when I try to do visualize.enm on a ranger model I get:

Error in predict.ranger(model$model, newdata = plot.df, type = "response") :
Error: Argument 'data' is required for non-quantile prediction.

Any idea what's up with that?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danlwarren/ENMTools/pull/79#issuecomment-369624212>,
or mute
the thread

**Comment by rdinnager** [comment]
Yes,  i should be branching if of the dev branch now,  shouldn't I? I will
remember to do that in the future.

On 2 Mar 2018 2:23 AM, "Dan Warren" <notifications@github.com> wrote:

Oh this highlighted something I borked up: the marginal plots function
wasn't standardizing so that the max predicted suitability was 1, which was
hiding a lot of the shape of the RF functions. I've now set it up so that
there's a "standardize" argument which defaults to TRUE. Unless that
argument is set to FALSE, marginal plots will now have a max response value
of 1.

This is on the dev branch right now, so if you want to do more tweaking on
a new branch you might want to update from there first.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danlwarren/ENMTools/pull/79#issuecomment-369626455>,
or mute
the thread

**Pull request merged**
