### PR TITLE
CRAN prep

### PR DESCRIPTION
**Pull request by rdinnager**
Hi Dan,

I made a bunch of changes to fix CMD check warnings, cleaned up some of the tests, and moved leaflet to Suggests. I also created an `install.extras()` function and a `check.package(pkg)` function, and used it in the interactive plot function, as well as now in the hypervolume functions. I also converted the `interactive.plot` functions into proper S3 methods so the user can now just type `interactive.plot`, instead of `interactive.plot.enmtools.model` etc. I've added \donttest{} to examples using extra packages, and added `skip_if_not_installed()` calls to tests that use extra packages too. 

CMD check has passed when I run it locally, but the main warning we get now is about the testdata folder being too big, which is is (44 mb). We should prune it down just to what we absolutely need for the tests. I should also note that the iberolacerta data is not in there, which is the one used in the current tests (the commented out one). We'll need to sort this out at some point.

I've now moved all the packages we can to Suggests. gh actions check is passing too!

### CODE REVIEW

**Comment by danlwarren** [comment]
Fantastic, thanks!

**Comment by danlwarren** [comment]
If I recall correctly the "testdata" folder doesn't really need to be uploaded to CRAN; I think I was only using it to demonstrate how to build species objects from .csv files and local rasters.

**Comment by rdinnager** [comment]
Except now that it is in `inst` I think it is officially part of the package and so does get uploaded (I think). But we can easily fix by adding the folder to `.Rbuildignore` I think, as long as the data isn't actually being used in any tests that will be run on CRAN.

**Comment by danlwarren** [comment]
Yeah I think we should do that, or maybe even just ditch it entirely.  We could do sample code for the readme that loads from GBIF and worldclim instead or something.

**Comment by rdinnager** [comment]
Oh right. I forgot you use the testdata in the Readme. Yes, I think let's move it back where it was and then just add it to `.Rbuildignore` and be done with it.

**Comment by danlwarren** [comment]
I’m actually in the process of fixing the readme so that it doesn’t need
this stuff.  Still a work in progress though!
-- 
Dan Warren
Email: dan.l.warren@gmail.com
Phone (US): 530-848-3809
Skype: dan.l.warren
Google Scholar
<https://scholar.google.com/citations?user=NTzu9c8AAAAJ&hl=en>  Orcid
<http://orcid.org/0000-0002-8747-2451>  ResearcherID
<http://www.researcherid.com/rid/B-3821-2010>  Scopus
<http://www.scopus.com/authid/detail.url?authorId=7202133982>

**Pull request merged**
