### PR TITLE
updated mahalanobis distance test w/ external test function

### PR DESCRIPTION
**Pull request by PhillRob**
I adjusted the following
- test function to accept data.frames and ENM tools species objects in external overlap.d2.function
- permutation in main function
- header clean up
- S3 output with plots of permutated distribution, thresholds for sig test and novelty test output

### CODE REVIEW

**Comment by danlwarren** [comment]
Hey, sorry it has taken me so long to get to this.  Things have been absolutely absurd for me lately, and I haven't even had a chance to look at it.  Unfortunately I probably won't before next week, either.

**Comment by PhillRob** [comment]
No problem, I have 2 time off work so keen to make progress on this.

**Comment by PhillRob** [comment]
Hi Darren, let me know if there is still time to add this to the package.

**Comment by danlwarren** [comment]
Sorry, there are still a ton of problems here.  Just a list of the first few things I noticed before I stopped working through it:

-The parameter names in the help file aren't the same as the ones the function is expecting.
-The d2.overlap function isn't actually being exported in the NAMESPACE file
-The example code doesn't work
-You've got the function set up to accept data frames, but that's not mentioned in the help file and also is inconsistent with how the rest of the package works
-You seem to be drawing env values from the enmtools.species objects themselves, which is not how they are supposed to work.  Either that or you're assuming that the first column for each object is the species name, which is also not how they're supposed to work.
-Using extract instead of add.env

I hope that I can say this without coming off as a jerk, but more broadly it just seems like it isn't set up to work together with ENMTools the way the rest of ENMTools is.  Supporting a package this large and complex is an awful lot of work already, and the only thing that makes that even remotely tractable is that Russell and I have been very consistent in how all these bits talk to each other.  Adding any new piece that doesn't fit within that framework is basically me volunteering to troubleshoot a whole bunch of new problems that I frankly don't have time to deal with.  I totally understand if you don't want to invest the time to make this work correctly with the rest of ENMTools, but that being the case I think you're better off releasing it as its own thing.

**Pull request closed without merging**
